// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSJufl59LO51qWt0t_Qa_hOYcVfJkVmM',
    appId: '1:285766486606:web:b36c87bd2294233628d11f',
    messagingSenderId: '285766486606',
    projectId: 'chamaapp-3f8b2',
    authDomain: 'chamaapp-3f8b2.firebaseapp.com',
    storageBucket: 'chamaapp-3f8b2.appspot.com',
    measurementId: 'G-1M5GEZ9KWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPSYDZg1yQtYAjWvPB5Sg1raRzw48JC4',
    appId: '1:285766486606:android:1dc7e3421aa3965628d11f',
    messagingSenderId: '285766486606',
    projectId: 'chamaapp-3f8b2',
    storageBucket: 'chamaapp-3f8b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj133n2McGmsfAv1Ds9HIBXpv1RdpS5Bw',
    appId: '1:285766486606:ios:ea1ff2b9b628507b28d11f',
    messagingSenderId: '285766486606',
    projectId: 'chamaapp-3f8b2',
    storageBucket: 'chamaapp-3f8b2.appspot.com',
    iosBundleId: 'com.example.chama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj133n2McGmsfAv1Ds9HIBXpv1RdpS5Bw',
    appId: '1:285766486606:ios:ea1ff2b9b628507b28d11f',
    messagingSenderId: '285766486606',
    projectId: 'chamaapp-3f8b2',
    storageBucket: 'chamaapp-3f8b2.appspot.com',
    iosBundleId: 'com.example.chama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhSJufl59LO51qWt0t_Qa_hOYcVfJkVmM',
    appId: '1:285766486606:web:321ed9eed992fef628d11f',
    messagingSenderId: '285766486606',
    projectId: 'chamaapp-3f8b2',
    authDomain: 'chamaapp-3f8b2.firebaseapp.com',
    storageBucket: 'chamaapp-3f8b2.appspot.com',
    measurementId: 'G-XJ7ENY3ZCT',
  );

}